name: Call composite action
on:
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: y-u-t-a/composite-action/init@main
        with:
          who-to-greet: "Yuta"
