name: Call composite action from another private repository
on:
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: root/github-actions-training
      - name: checkout action repo
        uses: actions/checkout@v3
        with:
          repository: y-u-t-a/composite-action
          token: ${{ secrets.GH_TOKEN }}
          path: root/composite-action
      - name: list file
        working-directory: root
        run: ls
      - name: call composite action
        uses: ../composite-action/actions/hello
