name: Call composite action from another private repository
on:
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkout action repo
        uses: actions/checkout@v3
        with:
          repository: y-u-t-a/composite-action
          token: ${{ secrets.GH_TOKEN }}
          path: ../composite-action
      - name: list file
        working-directory: ../
        run: ls
