name: Call composite action from another private repository
on:
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: y-u-t-a/composite-action/hello@main
        with:
          who-to-greet: "Yuta"
